# Generated by Django 3.2.6 on 2021-08-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_custom',
        ),
    ]
